version: "3"
services:
  markovserver:
    build: python
    volumes:
      - ./chainfiles:/app/chainfiles
      - ./log/gunicorn:/app/log/gunicorn
    environment:
      TZ: Asia/Tokyo
      PYTHONUNBUFFERED: "TRUE"
    env_file:
      - ./python/twitter.env
    restart: always
  nginxserver:
    build: vue
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
    links:
      - markovserver
    ports:
      - 8085:80
    environment:
      TZ: Asia/Tokyo
    restart: always
