version: "3"
services:
  markovserver:
    build: .
    volumes:
      - ./python:/scripts
      - ./chainfiles:/scripts/chainfiles
      - ./log/uwsgi:/scripts/log/uwsgi
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./python/twitter.env
    restart: always
    command: >
      /bin/bash -c "
      cd /scripts &&
      pip install pipenv &&
      pipenv install --system &&
      uwsgi --ini /scripts/uwsgi.ini"
  nginxserver:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
      - ./vue:/vue:ro
    links:
      - markovserver
    ports:
      - 8085:80
    environment:
      TZ: Asia/Tokyo
    restart: always
  htmlbBuilder:
    image: node:12
    volumes:
      - ./vue:/scripts
    command: >
      /bin/bash -c "
      cd /scripts &&
      npm clean-install &&
      npm run build"
